name: Sync Develop with Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email '<>'

      - name: Sync develop with main
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/tylerengland25/personal-website.git
          git checkout develop
          git merge origin/main
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
