name: Rebase develop on main

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

# Add these permissions
permissions:
  contents: write

jobs:
  rebase:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Git config
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Rebase develop
      run: |
        git fetch origin develop
        git checkout develop
        git rebase origin/main
        git push origin develop --force-with-lease
